{
 "title": "Faturamento/Vendas",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpidb" }
   ]
  },
  {
   "title": "Faturamento por canal",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": " SELECT CANAL_FATURAMENTO.CANAL,\r\n       SUM(CANAL_FATURAMENTO.TOTAL_VENDA) AS FATURAMENTO\r\n       FROM (\r\n       SELECT \r\n          SUM(FAT.TOTAL_VENDA) AS TOTAL_VENDA ,\r\n          CASE \r\n\t\t\tWHEN OPE_CODDEP =\t'001'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'004'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'006'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'007'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'008'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'009'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'010'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'011'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'012'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'013'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'015'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'019'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'020'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'021'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'022'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'023'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'024'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'026'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'027'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'028'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'029'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'030'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'033'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'034'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'035'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'036'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'037'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'038'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'039'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'040'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'041'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'042'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'043'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'044'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'045'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'046'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'047'\tTHEN\t'LOJA/BALCÃO'\r\n\t\t\tWHEN OPE_CODDEP =\t'002'\tTHEN\t'TELEVENDAS'\r\n\t\t\tWHEN OPE_CODDEP =\t'003'\tTHEN\t'ECOMMERCE'\r\n\t\t\tWHEN OPE_CODDEP =\t'016'\tTHEN\t'ECOMMERCE'\r\n\t\t\tWHEN OPE_CODDEP =\t'005'\tTHEN\t'DIGITAL'\r\n\t\t\tWHEN OPE_CODDEP =\t'014'\tTHEN\t'DIGITAL'\r\n\t\t\tWHEN OPE_CODDEP =\t'031'\tTHEN\t'DIGITAL'\r\n\t\t\tWHEN OPE_CODDEP =\t'032'\tTHEN\t'DIGITAL'\r\n\t\t\tELSE 'CANAL DESCONHECIDO'       \t\r\n          END AS CANAL          \r\n     FROM VW_FATURAMENTO FAT\r\nLEFT JOIN CADOPE CO ON FAT.COD_VENDEDOR = CO.OPE_CODOPE  \r\nLEFT JOIN CADDEP CD ON CO.OPE_CODDEP = CD.DEP_CODIGO\r\n    WHERE $__timeFilter(DATA_E_HORA)\r\n   GROUP BY CO.OPE_CODDEP\r\nUNION ALL\r\nSELECT SUM(FAT.TOTAL_VENDA) AS TOTAL_VENDA ,\r\n       'ECOMMERCE' AS CANAL\r\n  FROM VW_FATURAMENTO FAT\r\nLEFT JOIN CADOPE CO ON FAT.COD_VENDEDOR = CO.OPE_CODOPE  \r\nLEFT JOIN CADDEP CD ON CO.OPE_CODDEP = CD.DEP_CODIGO\r\nWHERE $__timeFilter(DATA_E_HORA)\r\n      AND CO.OPE_CODOPE = 'A27') AS CANAL_FATURAMENTO\r\n           GROUP BY CANAL_FATURAMENTO.CANAL"
    }
   ]
  },
  {
   "title": "Faturamento Lojas Físicas",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT CASE \r\n\tWHEN EMPRESA = '002' THEN 'AV. BRASIL'\r\n\tWHEN EMPRESA =  '006' THEN 'MATRIZ'\r\n\tWHEN EMPRESA =  '008' THEN 'ITU'\r\n\tWHEN EMPRESA =  '009' THEN 'SÃO JOSÉ DO RIO PRETO'\r\nEND AS EMPRESA,\r\n       SUM(TOTAL_VENDA) AS TOTAL\r\n  FROM VW_FATURAMENTO\r\n WHERE EMPRESA IN ('002','006','008','009')\r\n  AND $__timeFilter(DATA_E_HORA)\r\n  GROUP BY EMPRESA\r\n  order by SUM(TOTAL_VENDA) desc;"
    }
   ]
  },
  {
   "title": "Ranking Faturamento (TOP 10)",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "   SELECT CONCAT(FAT.COD_ITEM ,' - ', FAT.ITEM) AS Produto,\r\n          SUM(FAT.TOTAL_VENDA) AS Faturamento,\r\n          (   SELECT  SUM(IG.ITE_SALDOS - IG.ITE_SALEXT - IFNULL(IG.ITE_SALREG,0) - (IFNULL(IG.ITE_QTPD_V,0) + IFNULL(IG.ITE_QTPD_F,0) + IFNULL(IG.ITE_QTPD_P,0)))\r\n                FROM ITEGER IG\r\n               WHERE IG.ITE_CODITE = FAT.COD_ITEM ) AS Estoque\r\n     FROM VW_FATURAMENTO FAT\r\n    WHERE $__timeFilter(DATA_E_HORA) \r\n    GROUP BY CONCAT(FAT.COD_ITEM ,' - ', FAT.ITEM)\r\n    ORDER BY  SUM(FAT.TOTAL_VENDA) DESC\r\n    LIMIT 10;"
    }
   ]
  },
  {
   "title": "Ranking Quantidade (TOP 10)",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT CONCAT(FAT.COD_ITEM ,' - ', FAT.ITEM) as Produto,\r\n     SUM(FAT.QTD_ITEM) as \"Qtd. Venda\",\r\n     (   SELECT  SUM(IG.ITE_SALDOS - IG.ITE_SALEXT - IFNULL(IG.ITE_SALREG,0) - (IFNULL(IG.ITE_QTPD_V,0) + IFNULL(IG.ITE_QTPD_F,0) + IFNULL(IG.ITE_QTPD_P,0)))\r\n                FROM ITEGER IG\r\n               WHERE IG.ITE_CODITE = FAT.COD_ITEM) AS Estoque\r\n   FROM VW_FATURAMENTO FAT\r\n  WHERE $__timeFilter(FAT.DATA_E_HORA) \r\n  AND FAT.VALOR_UNITARIO > 20\r\n GROUP BY CONCAT(FAT.COD_ITEM ,' - ', FAT.ITEM)\r\norder by SUM(FAT.QTD_ITEM) desc\r\nlimit 10;"
    }
   ]
  },
  {
   "title": "Ranking Faturamento x Vendedor (TOP 10)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT NOME_VENDEDOR ,\r\n       SUM(TOTAL_VENDA) FATURAMENTO\r\n  FROM VW_FATURAMENTO\r\n  WHERE $__timeFilter(DATA_E_HORA) \r\n    -- and COD_VENDEDOR in ('A66','986','857','D58','594','560','620','598','555','561','D96','A32','A27','A25','918','B16','737','B77','B87','830','605','A57','B28','B64','C11','C09','946','A24','175','Z12','999')\r\nGROUP BY COD_VENDEDOR,NOME_VENDEDOR\r\nORDER BY FATURAMENTO DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}