{
 "title": "Gestão à vista - Importação de pedidos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "TIPO_PED", "query": "MAG, HUB, ANY, TOD" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpidb" }
   ]
  },
  {
   "title": "Total de integrações (Dia)",
   "type": "stat",
   "description": "Quantidade de pedidos integrados no período e origem selecionados",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "  SELECT COUNT(*) as total\r\nFROM EXTGOR WHERE FGO_DH_IMP BETWEEN $__timeFrom() AND $__timeTo() \r\n-- >= DATE_SUB(CURDATE(), INTERVAL 0 DAY)\r\nAND \r\nCASE \r\n  WHEN '$TIPO_PED' = 'MAG' THEN IFNULL(FGO_CODORI, 0) = '032'\r\n  WHEN '$TIPO_PED' = 'HUB' THEN IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033')\r\n  WHEN '$TIPO_PED' = 'ANY' THEN IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033')\r\n  ELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "Última integração GERAL em minuto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    ROUND(concat (TIMESTAMPDIFF(MINUTE,max(FGO_DH_IMP),CURTIME()))) as geral_integracao_min\r\n   FROM EXTGOR\r\n  WHERE DATE_SUB(CURTIME(), INTERVAL 1 HOUR)"
    }
   ]
  },
  {
   "title": "Última integração Magento em minuto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT \r\nround(concat(TIMESTAMPDIFF(MINUTE, max(IF(IFNULL(FGO_CODORI, 0) = '032', FGO_DH_IMP, 0)), CURTIME()))) as magento     \r\nFROM EXTGOR\r\nWHERE DATE_SUB(CURTIME(), INTERVAL 1 HOUR);"
    }
   ]
  },
  {
   "title": "Última Integração Hub em minuto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT \r\n     round(concat(TIMESTAMPDIFF(MINUTE, max(IF(IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033'), FGO_DH_IMP, 0)), CURTIME()))) as hub\r\nFROM EXTGOR\r\nWHERE DATE_SUB(CURTIME(), INTERVAL 1 HOUR);"
    }
   ]
  },
  {
   "title": "Última integração Anymarket em minuto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT \r\n    round(concat(TIMESTAMPDIFF(MINUTE, max(IF(IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033'), FGO_DH_IMP, 0)), CURTIME()))) as anymarket\r\nFROM EXTGOR\r\nWHERE DATE_SUB(CURTIME(), INTERVAL 1 HOUR);"
    }
   ]
  },
  {
   "title": "Media integrações Hora do Dia",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "SELECT\r\n    ROUND(\r\n        (\r\n       \t SELECT COUNT(*) FROM EXTGOR WHERE FGO_DH_IMP >= DATE_SUB(CURTIME(), INTERVAL 1 HOUR)\r\n            AND \r\n           \tCASE \r\n\t           \tWHEN '$TIPO_PED' = 'MAG' THEN IFNULL(FGO_CODORI, 0) = '032'\r\n\t           \tWHEN '$TIPO_PED' = 'HUB' THEN IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033')\r\n\t           \tWHEN '$TIPO_PED' = 'ANY' THEN IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033')\r\n\t           \tELSE TRUE \r\n           \tEND\r\n        )\r\n        /\r\n        (\r\n            SELECT COUNT(*)/7\r\n            FROM EXTGOR WHERE FGO_DH_IMP >= DATE_SUB(CURTIME(), INTERVAL 7 DAY)\r\n            AND CONCAT(LPAD(HOUR(FGO_DH_IMP), 2, 0), ' ', LPAD(MINUTE(FGO_DH_IMP), 2, 0)) >= CONCAT(LPAD(HOUR(DATE_SUB(CURTIME(), INTERVAL 1 HOUR)), 2, 0), ' ', LPAD(MINUTE(DATE_SUB(CURTIME(), INTERVAL 1 HOUR)), 2, 0))\r\n            AND CONCAT(LPAD(HOUR(FGO_DH_IMP), 2, 0), ' ', LPAD(MINUTE(FGO_DH_IMP), 2, 0)) <= CONCAT(LPAD(HOUR(CURTIME()), 2, 0), ' ', LPAD(MINUTE(CURTIME()), 2, 0))\r\n            AND \r\n           \tCASE \r\n\t           \tWHEN '$TIPO_PED'  = 'MAG' THEN IFNULL(FGO_CODORI, 0) = '032'\r\n\t           \tWHEN '$TIPO_PED' = 'HUB' THEN IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033')\r\n\t           \tWHEN '$TIPO_PED' = 'ANY' THEN IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033')\r\n\t           \tELSE TRUE \r\n           \tEND\r\n        )*100, 2\r\n    ) AS \"Media integrações Hora\""
    }
   ]
  },
  {
   "title": "Total de integrações por canal (Dia)",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT -- COUNT(*) AS \"Total Dia\",\r\n\tSUM(IF(IFNULL(FGO_CODORI, 0) = '032', 1, 0)) AS \"Magento\",\r\n\tSUM(IF(IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033'), 1, 0)) AS \"HUB\",\r\n\tSUM(IF(IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033'), 1, 0)) AS \"Anymarket\"\r\nFROM EXTGOR \r\nWHERE FGO_DH_IMP  BETWEEN $__timeFrom() AND $__timeTo() \r\n-- >= DATE_SUB(CURDATE(), INTERVAL 0 DAY)"
    }
   ]
  },
  {
   "title": "Integração de pedidos por minutos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "select cast(intervalo_10min as datetime) as time, pedido  FROM\r\n(\r\n  SELECT\r\n    DATE_FORMAT( \r\n  \tDATE_FORMAT(DATE_ADD(FGO_DH_IMP, INTERVAL 3 HOUR), '%Y-%m-%d %H:%i') - INTERVAL MOD(MINUTE(DATE_ADD(FGO_DH_IMP, INTERVAL 3 HOUR)), 10) MINUTE\r\n  \t, '%Y-%m-%d %H:%i')AS intervalo_10min,\r\n    COUNT(FGO_SEQFGO) AS pedido\r\nFROM\r\n    EXTGOR\r\nWHERE\r\n    FGO_DH_IMP BETWEEN $__timeFrom() AND $__timeTo() \r\n    AND \r\n    CASE \r\n      WHEN '$TIPO_PED' = 'MAG' THEN IFNULL(FGO_CODORI, 0) = '032'\r\n      WHEN '$TIPO_PED' = 'HUB' THEN IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033')\r\n      WHEN '$TIPO_PED' = 'ANY' THEN IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033')\r\n      ELSE TRUE \r\n    END\r\n   GROUP BY\r\n    intervalo_10min\r\nORDER BY\r\n    intervalo_10min\r\n    ) TB"
    }
   ]
  },
  {
   "title": "Consolidado de integrações por hora (Dia)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AUTCOM",
     "rawSql": "select \r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 00 THEN 1 ELSE 0 END) as \"00:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 01 THEN 1 ELSE 0 END) as \"1:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 02 THEN 1 ELSE 0 END) as \"2:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 03 THEN 1 ELSE 0 END) as \"3:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 04 THEN 1 ELSE 0 END) as \"4:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 05 THEN 1 ELSE 0 END) as \"5:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 06 THEN 1 ELSE 0 END) as \"6:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 07 THEN 1 ELSE 0 END) as \"7:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 08 THEN 1 ELSE 0 END) as \"8:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 09 THEN 1 ELSE 0 END) as \"9:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 10 THEN 1 ELSE 0 END) as \"10:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 11 THEN 1 ELSE 0 END) as \"11:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 12 THEN 1 ELSE 0 END) as \"12:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 13 THEN 1 ELSE 0 END) as \"13:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 14 THEN 1 ELSE 0 END) as \"14:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 15 THEN 1 ELSE 0 END) as \"15:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 16 THEN 1 ELSE 0 END) as \"16:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 17 THEN 1 ELSE 0 END) as \"17:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 18 THEN 1 ELSE 0 END) as \"18:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 19 THEN 1 ELSE 0 END) as \"19:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 20 THEN 1 ELSE 0 END) as \"20:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 21 THEN 1 ELSE 0 END) as \"21:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 22 THEN 1 ELSE 0 END) as \"22:00\",\r\nsum(CASE WHEN LPAD(HOUR(FGO_DH_IMP), 2, 0) = 23 THEN 1 ELSE 0 END) as \"23:00\",\r\nmax(FGO_DH_IMP) ultimo_pedido,\r\n(SELECT FORMAT((SELECT count(*) FROM EXTGOR WHERE FGO_DH_IMP >= DATE_SUB(CURTIME(), INTERVAL 1 HOUR))\r\n/\r\n(SELECT COUNT(*)/7\r\n   FROM EXTGOR\r\n  WHERE FGO_DH_IMP >=DATE_SUB(CURTIME(), INTERVAL 7 DAY)\r\n    AND CONCAT(LPAD(HOUR(FGO_DH_IMP), 2, 0), ' ', LPAD(MINUTE(FGO_DH_IMP), 2, 0)) >= CONCAT(LPAD(HOUR(DATE_SUB(CURTIME(), INTERVAL 1 HOUR)), 2, 0), ' ', LPAD(MINUTE(DATE_SUB(CURTIME(), INTERVAL 1 HOUR)), 2, 0))\r\n    AND CONCAT(LPAD(HOUR(FGO_DH_IMP), 2, 0), ' ', LPAD(MINUTE(FGO_DH_IMP), 2, 0)) <= CONCAT(LPAD(HOUR(CURTIME()), 2, 0), ' ', LPAD(MINUTE(CURTIME()), 2, 0)))*100, 2) AS PERCENT) media_7_dias\r\nfrom EXTGOR where FGO_DH_IMP >= CURRENT_DATE()\r\n    AND \r\n    CASE \r\n      WHEN '$TIPO_PED' = 'MAG' THEN IFNULL(FGO_CODORI, 0) = '032'\r\n      WHEN '$TIPO_PED' = 'HUB' THEN IFNULL(FGO_CODORI, 0) IN('03', '012', '025', '033')\r\n      WHEN '$TIPO_PED' = 'ANY' THEN IFNULL(FGO_CODORI, 0) NOT IN('032', '03', '012', '025', '033')\r\n      ELSE TRUE \r\n    END"
    }
   ]
  }
 ]
}